server:
  port: 8888

spring:
  application:
    name: auth-server

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.20.129:8848

  redis:
    host: 192.168.20.129
    database: 0

  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.20.129:3306/oauth2-sso?characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: dendy
    password: Zsh@727596853
    hikari:
      minimum-idle: 5
      idle-timeout: 600000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: MyHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1