server:
  port: 8020

spring:
  application:
    name: mall-order  #微服务名称

  #配置nacos注册中心地址
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.20.129:8848
        #namespace: bc50d386-8870-4a26-8803-0187486c57be
        #cluster-name: SH